# Generated by Django 2.2.2 on 2019-07-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='edited_json',
            field=models.TextField(blank=True, default='Json'),
        ),
        migrations.AlterField(
            model_name='file',
            name='json',
            field=models.TextField(default='Json'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
