# Generated by Django 2.2.1 on 2019-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='guid',
            field=models.CharField(default='old', max_length=20),
        ),
    ]
