# Generated by Django 2.2.1 on 2019-05-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_guid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='guid',
            new_name='uuid',
        ),
    ]
