# Generated by Django 2.2.2 on 2019-07-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190720_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uuid',
        ),
    ]
