# Generated by Django 2.2.2 on 2019-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
