# Generated by Django 2.2.2 on 2019-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='json',
            field=models.TextField(default='old'),
        ),
    ]
