const PREVIEW_WORD_CLOUD = state => state.PREVIEW_WORD_CLOUD
const PREVIEW_VERTICAL_BAR = state => state.PREVIEW_VERTICAL_BAR
const PREVIEW_VERTICAL_BAR_CATEGORIES = state => state.PREVIEW_VERTICAL_BAR_CATEGORIES

export default {
  PREVIEW_WORD_CLOUD,
  PREVIEW_VERTICAL_BAR,
  PREVIEW_VERTICAL_BAR_CATEGORIES
}
